name: My First awesome workflow yeah

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print a message
        run: echo "Hello World!"
      - name: Show Python version
        run: python --version
      - name: List current directory
        run: ls -la
        